version: "3"

services:

  app:
    build: ./app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  redis:
    image: redis:6.2.6

volumes:
  db_data: